
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 26 13:00:42 CET 2022
//----------------------------------------------------

package zoot.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int RETOURNE = 6;
  public static final int IDF = 31;
  public static final int JUSQUA = 23;
  public static final int CSTENTIERE = 29;
  public static final int OU = 21;
  public static final int PARENTHESEOUVRANTE = 10;
  public static final int PLUS = 13;
  public static final int EQUAL = 18;
  public static final int ECRIRE = 5;
  public static final int ALORS = 26;
  public static final int DIFFERENT = 19;
  public static final int FONCTIONS = 9;
  public static final int VIRGULE = 12;
  public static final int REPETER = 22;
  public static final int NEGATIVE = 15;
  public static final int NON = 16;
  public static final int INF = 17;
  public static final int POINTVIRGULE = 4;
  public static final int CSTBOOLEENE = 30;
  public static final int SINON = 28;
  public static final int TYPE = 32;
  public static final int VARIABLES = 8;
  public static final int EGALE = 7;
  public static final int FINREPETER = 24;
  public static final int PARENTHESEFERMANTE = 11;
  public static final int EOF = 0;
  public static final int MULT = 14;
  public static final int SI = 25;
  public static final int ET = 20;
  public static final int error = 1;
  public static final int DEBUT = 2;
  public static final int FINSI = 27;
  public static final int FIN = 3;
}

